apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: home
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.13.2  # Choose the version you need
    chart: ingress-nginx
    helm:
      values: |
        controller:
          hostNetwork: true
          hostPort:
            enabled: true
          kind: DaemonSet
          service:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
